name: dependency-review

on:
  - pull_request_target

jobs:
  shared:
    uses: ./.github/workflows/shared-dependency-review.yml
    with:
      allow-dependencies-licenses: pkg:npm/argparse
    permissions:
      contents: read
      pull-requests: write
