name: publish-eslint-config

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read
  id-token: write

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/@amezin/eslint-config-js-actions

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - run: npm --no-git-tag-version version from-git
        working-directory: packages/eslint-config

      - run: npm publish --provenance --access public
        working-directory: packages/eslint-config
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
